### ISSUE TITLE
Interpolation does not seem to be working

### ISSUE THREAD

**Issue by NaturalAI-InspireXT** [Terran-Source/interpolate-json#10]
I'm probably doing something wrong but here is my code below

`inputData[itemIndex] = {
                                              json: {
                                                  timestamp: '2023-03-17T17:20:42.093+00:00',
                                                  'Readable date': 'March 17th 2023, 5:20:42 pm',
                                                  'Readable time': '5:20:42 pm',
                                                  'Day of week': 'Friday',
                                                  Year: '2023',
                                                  Month: 'March',
                                                  'Day of month': '17',
                                                  Hour: '17',
                                                  Minute: '20',
                                                  Second: '42',
                                                  Timezone: 'GMT +00:00'
                                                }
                                           }
                                           
const paramterValue = [ { value1: '{{json.Minute}}', operation: 'equal', value2: '20' } ]

const paramterNew = interpolation.expand(parameterValue, inputData[itemIndex], {prefix: "{{",suffix: "}}",});
`

This does not replace the {{json.Minute}} template with the value 20

Any help greatly apreciated

**Comment by NaturalAI-InspireXT** [comment]
For anyone else having an issue, I figured out you cannot pass an array as the object to interpolate and replace on. Must be a string or json object only by the looks of it.

**Comment by turn-a-round** [comment]
Thanks for your observation and time to report it. Turns out, it's an easy fix. Deploying new patch, soon.

**Comment by turn-a-round** [comment]
Hi, fixed this issue in the new versions.
- Use `^2.3.0` if you're using Node v12
- Use latest if Node >v14

Thanks again :grinning:
