### ISSUE TITLE
✍️ Support for interpolation on arrays

### ISSUE THREAD

**Issue by JoshuaeKaiser** [Terran-Source/interpolate-json#11]
The expand method is not able to replace templates located within strings nested in arrays. Support seems to be only for JSON objects that don't have any data nested in arrays.

**Comment by turn-a-round** [comment]
Thanks for your observation and time to report it. Turns out, it's an easy fix. Deploying new patch, soon.

**Comment by JoshuaeKaiser** [comment]
@turn-a-round that's great. Will you notify on this thread when the latest deployment is on NMP? Much obliged. Great library.

**Comment by turn-a-round** [comment]
Hi, fixed this issue in the new versions.
- Use `^2.3.0` if you're using Node v12
- Use latest if Node >v14

Thanks again :grinning:

**Comment by JoshuaeKaiser** [comment]
@turn-a-round 

Is this fix available on npm version 3.0.0 ? Im running node 17. Still does not work for arrays for me.

**Comment by turn-a-round** [comment]
It's now available ^2.3.0 or ^3.0.0

Can you please provide an example, that you're trying?
