### ISSUE TITLE
It seems that some strings do not get interpolated when there is only one value

### ISSUE THREAD

**Issue by zaidamobiledevteam** [Terran-Source/interpolate-json#3]
**Describe the bug**
reading a json string values substitution with only one entry seems to fail, returning the ${variable} within the original string. 
Using two or more works as expected, even if the second variable does not exist within the values json

**To Reproduce**
1. Code snippet:
   
    `'const {interpolation} = require('interpolate-json');
// interpolation.debug();

var json1 = {variable: "test ${one}, ${two}, ${three}"};
//this works as expected
console.log("result 1");
console.log(interpolation.expand(json1, {one : "test1", two: "test2", three: "test3"}));

//this one fails
console.log("result 2");
console.log(interpolation.expand("this is ${language}" , {language: "english"}));

//same as above, just adding a second value, it works
console.log("result 3");
console.log(interpolation.expand("this is ${language} ${nowitworks}" , {language: "english", nowitworks:"ofcourse"}));

//correctly supresses the ${a} value and correctly replaces ${thing}
console.log("result 4");
console.log(interpolation.expand("${thing} it works without value ${a}"  , {thing: "there is only one"}));
'`
2. Run command: `$ ....`
3. Error: `Exception:...`

**Expected behavior**
console.log(interpolation.expand("this is ${language}" , {language: "english"}));
should output 
"this is english"

**Screenshots**
![image](https://user-images.githubusercontent.com/58249454/80206917-d926cd00-85f2-11ea-9aee-f978d8e30d16.png)

**Environment (please complete the following information):**
 - OS: 
linux mint 19.3 64bit
 - Node.js version
v13.9.0
 - Version
    "interpolate-json": "^2.0.1"

**Additional context**
nothing else, this library is exactly what i need but its not working for that specific case.

workaround: just add a ${x} at the end as a white space:
interpolation.expand( localeStrings.settinglanguage+"${a}",   {language: lang_name} )

**Comment by turn-a-round** [comment]
Thanks for your detailed description. Looking into it. :)

**Comment by turn-a-round** [comment]
Please upgrade to `"interpolate-json": "^2.0.2"` and check.
Kindly give your feedback. :)

**Comment by turn-a-round** [comment]
Closing the issue...
